Entity: RestrictedTrafficArea  
=============================
  

Global description: **An area of a city in which the traffic generated by cars or any other kind of vehicles is subjected to limitation.**  

This is taken from: https://github.com/smart-data-models/dataModel.Transportation/blob/master/RestrictedTrafficArea/doc/spec.md

## List of properties  


- `address`: The mailing address  
- `alternateName`: An alternative name for this item  
- `areaServed`: The geographic area where a service or offered item is provided  
- `category`: Restricted traffic area's category(ies). The purpose of this field is to allow to tag, generally speaking, restricted traffic area entities. Particularities and detailed descriptions should be found under the corresponding specific attributes.  
- `dataProvider`: A sequence of characters identifying the provider of the harmonised data entity.  
- `dateCreated`: Entity creation timestamp. This will usually be allocated by the storage platform.  
- `dateModified`: Timestamp of the last modification of the entity. This will usually be allocated by the storage platform.  
- `description`: A description of this item  
- `id`: Unique identifier of the entity  
- `location`: Geojson reference to the item. It can be Point, LineString, Polygon, MultiPoint, MultiLineString or MultiPolygon  
- `name`: The name of this item.  
- `notAllowedVehicleType`: Vehicle type(s) not allowed to cross the restricted traffic area.  
- `owner`: A List containing a JSON encoded sequence of characters referencing the unique Ids of the owner(s)  
- `regulation`: A URL pointing to the regulation for the specific restricted traffic area.  
- `restrictionExceptions`: Individual vehicle type allowed to cross the restricted traffic area in a specific time slot.  
- `restrictionValidityHours`: Days of the week and hours in which the traffic restriction is active.  
- `security`: Security aspects provided by this restricted traffic area.  
- `seeAlso`: list of uri pointing to additional resources about the item  
- `source`: A sequence of characters giving the original source of the entity data as a URL. Recommended to be the fully qualified domain name of the source provider, or the URL to the source object.  
- `specialRestrictions`: Individual vehicle type not allowed to cross the restricted traffic area in a specific time slot.  
- `type`: NGSI Entity type. It has to be RestrictedTrafficArea  
- `validityEndDate`: The date at which the restriction is dismissed.  
- `validityStartDate`: The date from which the restriction is applied.  
  

Required properties  
- `id`  
- `type`  
  
